import {
  BadRequestException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { generateBatchCode } from 'src/common/utils/generate-batch-code.util';
import { SkuUtil } from 'src/common/utils/generate-product-sku.util';
import { BaseUnitRepository } from './base-unit/base-unit.repository';
import { CreateProductDto } from './dto/create-product.dto';
import { GetBatchesDto } from './dto/get-batches.dto';
import { GetProductsDto } from './dto/get-products.dto';
import { UpdateBatchDto } from './dto/update-batch.dto';
import { UpdateProductDto } from './dto/update-product.dto';
import { ProductRepository } from './product.repository';

@Injectable()
export class ProductService {
  constructor(
    private readonly productRepository: ProductRepository,
    private readonly baseUnitRepository: BaseUnitRepository,
  ) {}

  async createProduct(dto: CreateProductDto) {
    const autoGeneratedSku = SkuUtil.generateProductSku(dto.name || '');
    const existing = await this.productRepository.findBySku(autoGeneratedSku);
    if (existing) {
      throw new BadRequestException('Mã SKU đã tồn tại trên hệ thống');
    }
    const baseUnit = await this.baseUnitRepository.findById(dto.baseUnitId);
    if (!baseUnit) {
      throw new NotFoundException('Đơn vị tính không tồn tại');
    }
    return await this.productRepository.create({
      ...dto,
      sku: autoGeneratedSku,
    });
  }

  async updateProduct(id: number, dto: UpdateProductDto) {
    const existing = await this.productRepository.findById(id);
    if (!existing) {
      throw new NotFoundException('Sản phẩm không tồn tại');
    }
    if (!existing.isActive) {
      throw new NotFoundException(
        'Sản phẩm này đã bị xóa hoặc ngừng kinh doanh',
      );
    }
    return await this.productRepository.update(id, dto);
  }

  async getProduct(id: number) {
    const product = await this.productRepository.findOneWithBatches(id);
    if (!product) {
      throw new NotFoundException('Sản phẩm không tồn tại');
    }
    if (!product.isActive) {
      throw new NotFoundException(
        'Sản phẩm này đã bị xóa hoặc ngừng kinh doanh',
      );
    }
    return product;
  }

  async getProducts(filter: GetProductsDto) {
    return await this.productRepository.findAll(filter);
  }

  async removeProduct(id: number) {
    const product = await this.productRepository.findById(id);
    if (!product) {
      throw new NotFoundException('Sản phẩm không tồn tại');
    }
    if (!product.isActive) {
      throw new NotFoundException(
        'Sản phẩm này đã bị xóa hoặc ngừng kinh doanh',
      );
    }
    return await this.productRepository.softDelete(id);
  }

  async getProductsInactive() {
    return await this.productRepository.findAllInactive();
  }

  async restoreProduct(id: number) {
    const product = await this.productRepository.findById(id);
    if (!product) {
      throw new NotFoundException('Sản phẩm không tồn tại');
    }
    return await this.productRepository.restore(id);
  }

  // --- Batch Services ---

  async getBatches(filter: GetBatchesDto) {
    return await this.productRepository.findAllBatches(filter);
  }

  async getBatch(id: number) {
    const batch = await this.productRepository.findBatchById(id);
    if (!batch) {
      throw new NotFoundException('Lô hàng không tồn tại');
    }
    return batch;
  }

  async updateBatch(id: number, dto: UpdateBatchDto) {
    const batch = await this.productRepository.findBatchById(id);
    if (!batch) {
      throw new NotFoundException('Lô hàng không tồn tại');
    }

    let centralWarehouseId: number | undefined;
    if (dto.initialQuantity) {
      centralWarehouseId =
        await this.productRepository.findCentralWarehouseId();
      if (!centralWarehouseId) {
        throw new BadRequestException(
          'Không tìm thấy kho tổng để cập nhật số lượng',
        );
      }
    }

    return await this.productRepository.updateBatch(
      id,
      dto,
      centralWarehouseId,
    );
  }

  /**
   * Centralized Batch Creation Logic
   * Used by Inbound Module and other internal processes.
   * Does NOT accept arbitrary quantity. Quantity is handled by specific flows (Inbound/Adjustment).
   */
  async createBatch(productId: number, imageUrl?: string) {
    const product = await this.productRepository.findById(productId);
    if (!product) {
      throw new NotFoundException('Sản phẩm không tồn tại');
    }

    const generatedBatchCode = generateBatchCode(product.sku);

    // FEFO Logic: Calculate expiry date from TODAY
    const today = new Date();
    const expiryDate = new Date(today);
    expiryDate.setDate(today.getDate() + product.shelfLifeDays);
    const expiryDateStr = expiryDate.toISOString().split('T')[0];

    return await this.productRepository.createBatch({
      productId: productId,
      batchCode: generatedBatchCode,
      expiryDate: expiryDateStr,
      imageUrl: imageUrl,
    });
  }
}
